name: beployblog

on: 

  workflow_dispatch:
 
jobs:

  deploy-blog:

    runs-on: ubuntu-latest

    

    steps:

      - uses: actions/checkout@v4

      - name: Setup environment

      

        uses: actions/setup-node@v4

        with:

         node-version: 18

      

      - name: Install Hexo

        run: |

      

          npm i -g hexo hexo-cli

      - name: Pull blog source

        run: |

          git clone https://github.com/dpkg123/blogbackup

      - name: Build blog

        run: |

          cd blogbackup

          sudo rm -rf .git*

          npm install --force --save

          hexo cl && hexo g

      - name: Upload blog to artifact

        uses: actions/upload-artifact@v3

        with:

          name: blog-html

          path: blogbackup/public/*
