name: Sync from upstream

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    strategy:
      fail-fast: false
      matrix:
        include:
        - owner: Voxelum
          repo:  x-minecraft-launcher
          arch: amd64
        - owner: Voxelum
          repo:  x-minecraft-launcher
          arch: arm64
        - owner: chrismaltby
          repo:  gb-studio
          arch: amd64
        - owner: qier222
          repo:  YesPlayMusic
          arch: amd64
        - owner: qier222
          repo:  YesPlayMusic
          arch: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: sudo apt update && sudo apt install jq reprepro -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: sync
        run: bash debian/sync.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.arch }}
          OWNER: ${{ matrix.owner }}
          REPO: ${{ matrix.repo }}

        
