name: Sync from upstream

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build-deb-amd64:
    strategy:
      fail-fast: false
      matrix:
        include:
        - owner: Voxelum
          repo:  x-minecraft-launcher
          arch: amd64
        - owner: Voxelum
          repo:  x-minecraft-launcher
          arch: arm64
        - owner: qier222
          repo:  YesPlayMusic
          arch: amd64
        - owner: qier222
          repo:  YesPlayMusic
          arch: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Tools
        run: sudo apt update && sudo apt install jq reprepro -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: sync
        run: bash debian/sync.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.arch }}
          OWNER: ${{ matrix.owner }}
          REPO: ${{ matrix.repo }}
      - name: add package
        run: |
          cd debian
          sed -i 's/SignWith: C98C969E/#SignWith: C98C969E/g' conf/distributions
          reprepro includedeb stable ../*.deb
      - name: commit updates
        run: |
          git config user.name "renovate[bot] "
          git pull
          git config user.email "29139614+renovate[bot]@users.noreply.github.com"
          git pull
          git config --global --add safe.directory /github/workspace
          git pull
          git add .
          git commit -m "Bump packages"
          git pull --rebase
      - name: GitHub Push
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          


  gb:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs: build-deb-amd64
    steps:
      - name: Install Build Tools
        run: sudo apt update && sudo apt install jq reprepro -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: sync
        run: bash debian/sync-gb-studio.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: add package
        run: |
          cd debian
          sed -i 's/SignWith: C98C969E/#SignWith: C98C969E/g' conf/distributions
          reprepro includedeb stable ../*.deb
      - name: commit updates
        run: |
          git config user.name "renovate[bot] "
          git pull 
          git config user.email "29139614+renovate[bot]@users.noreply.github.com"
          git pull 
          git config --global --add safe.directory /github/workspace
          git pull 
          git add .
          git commit -m "Bump packages"
          git pull 
      - name: GitHub Push
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
