name: deploy blog (Testing)

on:
   push:

    branches: main


jobs:

  deploy-blog:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup environment

        run: |
          sudo apt update
          sudo apt install -y git rsync npm nodejs tar zip unzip xz-utils
          npm i -g hexo hexo-cli
      - name: Pull blog source

        run: |
          git clone https://github.com/dpkg123/blogbackup
      - name: Build blog
        run: |
          cd blogbackup
          cd themes # 进入原Hexo博客根目录下themes文件夹

          git clone https://github.com/jackhanyuan/hexo-theme-new-yilia.git

          rsync -avb --suffix=_bak hexo-theme-new-yilia/* .. # 同步new-yilia主题到原Hexo博客根目录，如果有冲突会自动备份冲突文件（以_bak结尾）。

          rm -rf hexo-theme-new-yilia

          npm install
          sudo rm -rf .git*
          hexo cl && hexo g
      - name: Upload blog to artifact

        uses: actions/upload-artifact@v3

        with:

          name: blog-html

          path: blogbackup/public/*
         
